CREATE SEQUENCE IF NOT EXISTS USER_ID_SEQ START WITH 50 INCREMENT BY 50;

CREATE TABLE USERS
(
    USER_ID                    BIGINT       NOT NULL,
    FIRST_NAME                 VARCHAR(255) NOT NULL,
    LAST_NAME                  VARCHAR(255) NOT NULL,
    EMAIL                      VARCHAR(255) NOT NULL,
    PASSWORD                   VARCHAR(255) NOT NULL,
    PHONE_NUMBER               VARCHAR(255) NOT NULL,
    SEX                        BOOLEAN      NOT NULL,
    PERSONAL_ID_NUMBER         VARCHAR(255) NOT NULL,
    COUNTRY                    VARCHAR(255) NOT NULL,
    CITY                       VARCHAR(255) NOT NULL,
    ADDRESS_LINE               VARCHAR(255) NOT NULL,
    USER_TYPE                  VARCHAR(255) NOT NULL,
    ZIP_CODE                   VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH              DATE         NOT NULL,
    IS_ENABLED                 BOOLEAN      NOT NULL,
    IS_NON_EXPIRED             BOOLEAN      NOT NULL,
    IS_NON_LOCKED              BOOLEAN      NOT NULL,
    IS_CREDENTIALS_NON_EXPIRED BOOLEAN      NOT NULL,
    LANGUAGE                   VARCHAR(255) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);

CREATE INDEX IDX_EMAIL ON USERS (EMAIL);

CREATE INDEX IDX_EMAIL_USER_TYPE ON USERS (EMAIL, USER_TYPE);

CREATE INDEX IDX_USER_TYPE ON USERS (USER_TYPE);

CREATE SEQUENCE IF NOT EXISTS TOKEN_ID_SEQ START WITH 50 INCREMENT BY 50;

CREATE TABLE TOKENS
(
    TOKEN_ID     BIGINT                      NOT NULL,
    TOKEN        VARCHAR(255)                NOT NULL,
    CREATED_AT   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    EXPIRES_AT   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONFIRMED_AT TIMESTAMP WITHOUT TIME ZONE,
    USER_ID      BIGINT                      NOT NULL,
    CONSTRAINT PK_TOKENS PRIMARY KEY (TOKEN_ID)
);

CREATE INDEX IDX_TOKEN ON TOKENS (TOKEN);

ALTER TABLE TOKENS
    ADD CONSTRAINT FK_TOKENS_ON_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

CREATE SEQUENCE IF NOT EXISTS TREATMENT_ID_SEQ START WITH 50 INCREMENT BY 50;

CREATE TABLE TREATMENTS
(
    TREATMENT_ID          BIGINT       NOT NULL,
    TREATMENT_NAME        VARCHAR(255) NOT NULL,
    TREATMENT_DESCRIPTION VARCHAR(255) NOT NULL,
    TREATMENT_PRICE       BIGINT       NOT NULL,
    CONSTRAINT PK_TREATMENTS PRIMARY KEY (TREATMENT_ID)
);

CREATE INDEX IDX_TREATMENT_NAME ON TREATMENTS (TREATMENT_NAME);

CREATE SEQUENCE IF NOT EXISTS FILE_ID_SEQ START WITH 50 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS INVOICE_ID_SEQ START WITH 50 INCREMENT BY 50;

CREATE TABLE INVOICES
(
    INVOICE_ID     BIGINT       NOT NULL,
    PRICE          BIGINT,
    IS_PAID        BOOLEAN      NOT NULL,
    PAYMENT_METHOD VARCHAR(255) NOT NULL,
    PAYMENT_DATE   DATE,
    PAYMENT_STATUS VARCHAR(255) NOT NULL,
    CONSTRAINT PK_INVOICES PRIMARY KEY (INVOICE_ID)
);

CREATE TABLE APPOINTMENTS
(
    APPOINTMENT_ID         BIGINT                 NOT NULL,
    PATIENT_ID             BIGINT                 NOT NULL,
    DOCTOR_ID              BIGINT                 NOT NULL,
    APPOINTMENT_DATE       DATE                   NOT NULL,
    APPOINTMENT_START_TIME TIME WITHOUT TIME ZONE NOT NULL,
    APPOINTMENT_END_TIME   TIME WITHOUT TIME ZONE NOT NULL,
    IS_CONFIRMED           BOOLEAN                NOT NULL,
    IS_CANCELLED           BOOLEAN                NOT NULL,
    DESCRIPTION            VARCHAR(255),
    INVOICE_ID             BIGINT,
    VERSION                BIGINT,
    CONSTRAINT PK_APPOINTMENTS PRIMARY KEY (APPOINTMENT_ID)
);

ALTER TABLE APPOINTMENTS
    ADD CONSTRAINT UC_APPOINTMENTS_INVOICE UNIQUE (INVOICE_ID);

CREATE INDEX IDX_DATE_IS_CANCELLED ON APPOINTMENTS (APPOINTMENT_DATE, IS_CANCELLED);

CREATE INDEX IDX_DOCTOR_ID_DATE_IS_CANCELLED ON APPOINTMENTS (DOCTOR_ID, APPOINTMENT_DATE, IS_CANCELLED);

CREATE INDEX IDX_DOCTOR_ID_IS_CANCELLED ON APPOINTMENTS (DOCTOR_ID, IS_CANCELLED);

CREATE INDEX IDX_IS_CONFIRMED_DATE ON APPOINTMENTS (IS_CONFIRMED, APPOINTMENT_DATE);

CREATE INDEX IDX_PATIENT_ID_IS_CANCELLED ON APPOINTMENTS (PATIENT_ID, IS_CANCELLED);

ALTER TABLE APPOINTMENTS
    ADD CONSTRAINT FK_APPOINTMENTS_ON_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES USERS (USER_ID);

ALTER TABLE APPOINTMENTS
    ADD CONSTRAINT FK_APPOINTMENTS_ON_INVOICE FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES (INVOICE_ID);

ALTER TABLE APPOINTMENTS
    ADD CONSTRAINT FK_APPOINTMENTS_ON_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES USERS (USER_ID);

CREATE TABLE FILES
(
    FILE_ID        BIGINT                      NOT NULL,
    FILE_DATA      OID                         NOT NULL,
    FILE_NAME      VARCHAR(255)                NOT NULL,
    APPOINTMENT_ID BIGINT                      NOT NULL,
    UPLOADED_AT    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UPDATED_AT     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT PK_FILES PRIMARY KEY (FILE_ID)
);

ALTER TABLE FILES
    ADD CONSTRAINT UC_FILES_FILE_NAME UNIQUE (FILE_NAME);

ALTER TABLE FILES
    ADD CONSTRAINT FK_FILES_ON_APPOINTMENT FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENTS (APPOINTMENT_ID);

CREATE SEQUENCE IF NOT EXISTS SUPPLY_ID_SEQ START WITH 50 INCREMENT BY 50;

CREATE TABLE SUPPLIES
(
    SUPPLY_ID BIGINT           NOT NULL,
    NAME      VARCHAR(255)     NOT NULL,
    QUANTITY  DOUBLE PRECISION NOT NULL,
    LINK      VARCHAR(255),
    CONSTRAINT PK_SUPPLIES PRIMARY KEY (SUPPLY_ID)
);

CREATE INDEX IDX_NAME ON SUPPLIES (NAME);

CREATE SEQUENCE IF NOT EXISTS REFERRAL_ID_SEQ START WITH 50 INCREMENT BY 50;

CREATE TABLE REFERRALS
(
    REFERRAL_ID           BIGINT       NOT NULL,
    PROCEDURE_NAME        VARCHAR(255) NOT NULL,
    PROCEDURE_DESCRIPTION VARCHAR(255) NOT NULL,
    DOCTOR_NAME           VARCHAR(255),
    CLINIC_NAME           VARCHAR(255) NOT NULL,
    CLINIC_ADDRESS        VARCHAR(255),
    APPOINTMENT_ID        BIGINT       NOT NULL,
    CONSTRAINT PK_REFERRALS PRIMARY KEY (REFERRAL_ID)
);

ALTER TABLE REFERRALS
    ADD CONSTRAINT FK_REFERRALS_ON_APPOINTMENT FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENTS (APPOINTMENT_ID);

CREATE SEQUENCE IF NOT EXISTS PRESCRIPTION_ID_SEQ START WITH 50 INCREMENT BY 50;

CREATE TABLE PRESCRIPTIONS
(
    PRESCRIPTION_ID BIGINT       NOT NULL,
    MEDICINE        VARCHAR(255) NOT NULL,
    DOSAGE          VARCHAR(255) NOT NULL,
    APPOINTMENT_ID  BIGINT       NOT NULL,
    CONSTRAINT PK_PRESCRIPTIONS PRIMARY KEY (PRESCRIPTION_ID)
);

ALTER TABLE PRESCRIPTIONS
    ADD CONSTRAINT FK_PRESCRIPTIONS_ON_APPOINTMENT FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENTS (APPOINTMENT_ID);

CREATE SEQUENCE IF NOT EXISTS AVAILABILITY_ID_SEQ START WITH 50 INCREMENT BY 50;

CREATE TABLE AVAILABILITIES
(
    AVAILABILITY_ID         BIGINT                 NOT NULL,
    DOCTOR_ID               BIGINT                 NOT NULL,
    AVAILABILITY_DATE       DATE                   NOT NULL,
    AVAILABILITY_START_TIME TIME WITHOUT TIME ZONE NOT NULL,
    AVAILABILITY_END_TIME   TIME WITHOUT TIME ZONE NOT NULL,
    IS_CONFIRMED            BOOLEAN                NOT NULL,
    BRAKE_TIME_START        TIME WITHOUT TIME ZONE,
    BRAKE_TIME_END          TIME WITHOUT TIME ZONE,
    VERSION                 BIGINT,
    CONSTRAINT PK_AVAILABILITIES PRIMARY KEY (AVAILABILITY_ID)
);

CREATE INDEX IDX_DOCTOR_ID_DATE_START_TIME_END_TIME ON AVAILABILITIES (DOCTOR_ID, AVAILABILITY_DATE,
                                                                       AVAILABILITY_START_TIME, AVAILABILITY_END_TIME);

CREATE INDEX IDX_DOCTOR_ID_DATE_START_TIME_END_TIME_BRAKE_TIME ON AVAILABILITIES (DOCTOR_ID, AVAILABILITY_DATE,
                                                                                  AVAILABILITY_START_TIME,
                                                                                  AVAILABILITY_END_TIME,
                                                                                  BRAKE_TIME_START, BRAKE_TIME_END);

ALTER TABLE AVAILABILITIES
    ADD CONSTRAINT FK_AVAILABILITIES_ON_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES USERS (USER_ID);

CREATE INDEX IDX_DOCTOR_ID ON AVAILABILITIES (DOCTOR_ID);

CREATE SEQUENCE IF NOT EXISTS APPOINTMENT_ID_SEQ START WITH 50 INCREMENT BY 50;
