spring.jpa.database=h2
spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=create-drop


spring.datasource.url=jdbc:h2:mem:db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.defer-datasource-initialization=true

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=${EMAIL_USERNAME_DEV}
spring.mail.password=${EMAIL_PASSWORD_DEV}
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=*